# Generated by Django 5.0.3 on 2024-04-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mail_admin", "0002_auto_20190709_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailbox",
            name="from_email",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Example: MailBot &lt;mailbot@yourdomain.com&gt;<br />'From' header to set for outgoing email.<br /><br />If you do not use this e-mail inbox for outgoing mail, this setting is unnecessary.<br />If you send e-mail without setting this, your 'From' header will'be set to match the setting `DEFAULT_FROM_EMAIL`.<br />Required for Office 365 mailbox",
                max_length=255,
                null=True,
                verbose_name="From email",
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="uri",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Example: imap+ssl://myusername:mypassword@someserver <br /><br />Internet transports include 'imap' and 'pop3'; common local file transports include 'maildir', 'mbox', and less commonly 'babyl', 'mh', and 'mmdf'. <br /><br /><br />For Office 365 email accounts use: 'office365:username@example.com:/?client_id_key=<client_id_key>&client_secret_key=<client_secret_key>&client_app_id=<client_app_id_str>'. Default values of client_id_key and client_secret_key are 'O365_CLIENT_ID', and 'O365_CLIENT_SECRET'. When all 3 are provided it will lookup client_id_key/secret_key values from client_app_id configuration.<br />supports only on-behalf-of-a-user; thus requires user's auth & consent in a separate authentication flow via console/ or web-browser.<br />Be sure to urlencode your username and password should they contain illegal characters (like @, :, etc).<br />",
                max_length=255,
                null=True,
                verbose_name="URI",
            ),
        ),
    ]
