# Generated by Django 5.0.3 on 2024-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mail_admin", "0003_alter_mailbox_from_email_alter_mailbox_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingemail",
            name="message_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Internet Message-ID for outgoing draft/email",
                max_length=255,
                null=True,
                verbose_name="OutgoingEmail ID",
            ),
        ),
    ]
