# Generated by Django 2.2.24 on 2024-08-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_mail_admin", "0003_alter_mailbox_from_email_alter_mailbox_uri"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="incomingemail",
            unique_together={("mailbox", "message_id")},
        ),
    ]
