# Generated by Django 5.0.9 on 2024-10-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mail_admin', '0005_incomingemail_send_datetime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incomingattachment',
            index=models.Index(fields=['message'], name='django_mail_message_dea8fb_idx'),
        ),
    ]
