# Generated by Django 2.2.24 on 2026-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mail_admin", "0007_create_emailaddressoauthmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailbox",
            name="uri",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Example: imap+ssl://myusername:mypassword@someserver <br /><br />Internet transports include 'imap' and 'pop3'; common local file transports include 'maildir', 'mbox', and less commonly 'babyl', 'mh', and 'mmdf'. <br /><br /><br />For Office 365 email accounts use: 'office365:username@example.com:/?client_id_key=<client_id_key>&client_secret_key=<client_secret_key>&client_app_id=<client_app_id_str>'. Default values of client_id_key and client_secret_key are 'O365_CLIENT_ID', and 'O365_CLIENT_SECRET'. When all 3 are provided it will lookup client_id_key/secret_key values from client_app_id configuration.<br />supports only on-behalf-of-a-user; thus requires user's auth & consent in a separate authentication flow via console/ or web-browser.<br /><br />For Nylas email accounts use: 'nylas:username@example.com:/?grant_id=<grant_id>'. The NYLAS_API_KEY must be configured in Django settings.py. Nylas provides unified API access to Gmail, Outlook, IMAP and other providers.<br />Be sure to urlencode your username and password should they contain illegal characters (like @, :, etc).<br />",
                max_length=255,
                null=True,
                verbose_name="URI",
            ),
        ),
    ]
