# Generated by Django 2.2.24 on 2026-01-14 21:38

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("django_mail_admin", "0007_create_emailaddressoauthmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailbox",
            name="uri",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Example: imap+ssl://myusername:mypassword@someserver <br /><br />Internet transports include 'imap' and 'pop3'; common local file transports include 'maildir', 'mbox', and less commonly 'babyl', 'mh', and 'mmdf'. <br /><br /><br />For Office 365 email accounts use: 'office365:username@example.com:/?client_id_key=<client_id_key>&client_secret_key=<client_secret_key>&client_app_id=<client_app_id_str>'. Default values of client_id_key and client_secret_key are 'O365_CLIENT_ID', and 'O365_CLIENT_SECRET'. When all 3 are provided it will lookup client_id_key/secret_key values from client_app_id configuration.<br />supports only on-behalf-of-a-user; thus requires user's auth & consent in a separate authentication flow via console/ or web-browser.<br /><br />For Nylas email accounts use: 'nylas:username@example.com:/?grant_id=<grant_id>'. The NYLAS_API_KEY must be configured in Django settings.py. Nylas provides unified API access to Gmail, Outlook, IMAP and other providers.<br />Be sure to urlencode your username and password should they contain illegal characters (like @, :, etc).<br />",
                max_length=255,
                null=True,
                verbose_name="URI",
            ),
        ),
        migrations.CreateModel(
            name="NylasGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grant_id",
                    models.CharField(
                        help_text="Nylas grant identifier",
                        max_length=255,
                        unique=True,
                        verbose_name="Grant ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email address associated with this grant",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Email provider (e.g., google, microsoft, imap)",
                        max_length=50,
                        verbose_name="Email Provider",
                    ),
                ),
                (
                    "grant_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("needs_reauth", "Needs Re-authentication"),
                            ("expired", "Expired"),
                        ],
                        default="valid",
                        help_text="Current status of the grant",
                        max_length=50,
                        verbose_name="Grant Status",
                    ),
                ),
                (
                    "metadata",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional grant information from Nylas",
                        verbose_name="Grant Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the grant was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the grant was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "mailbox",
                    models.OneToOneField(
                        help_text="The mailbox associated with this Nylas grant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nylas_grant",
                        to="django_mail_admin.Mailbox",
                        verbose_name="Mailbox",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nylas Grant",
                "verbose_name_plural": "Nylas Grants",
                "ordering": ["-updated_at"],
            },
        ),
    ]
